kind: Job
apiVersion: batch/v1
metadata:
  name: hisup-train
spec:
  template:
    spec:
      containers:
      - name: hisup-train
        image: "csalomonsen/hisup-springfield:0.3-dev"
        # command: ["sh", "-c", "/storage/experiments/hisup/init.sh"]
        command: ["sh", "-c", "/storage/experiments/hisup/init.sh", "/storage/experiments/hisup/hisup-demo.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
