kind: Job
apiVersion: batch/v1
metadata:
  name: hisup-simple
spec:
  template:
    spec:
      containers:
      - name: hisup-simple
        image: "pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel"
        command: ["sh", "/storage/experiments/hisup/run-simple.sh"]
        workingDir: /storage/experiments/hisup
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: regcred
  backoffLimit: 0
