kind: Job
apiVersion: batch/v1
metadata:
  name: hisup-inference
spec:
  template:
    spec:
      containers:
      - name: hisup-inference
        image: "csalomonsen/hisup-springfield:0.2-release"
        command: ["sh", "hisup-demo.sh"]
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: storage
      restartPolicy: OnFailure
  backoffLimit: 0
